# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    # список доступных адаптеров
    adapters:
        public:
            local:
                directory: '%kernel.project_dir%/public/files'
        private:
            local:
                directory: '%kernel.project_dir%/private/files'

    # используемые адаптеры
    filesystems:
        public_fs:
            adapter: public
            alias: public_fs
        private_fs:
            adapter: private
            alias: private_fs
